name: n2v

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10.14
  - pip
  - setuptools
  - wheel
  - numpy=1.26.4
  - scipy=1.14.0rc2
  - pandas=2.2.2
  - mkl
  - mkl_fft
  - mkl_random
  - tifffile=2023.4.12
  - pillow
  - imagecodecs
  - imageio
  - matplotlib-base=3.8.4
  - matplotlib-inline
  - seaborn
  - pytorch=2.3.1
  - torchvision=0.18.1
  - pytorch-cuda=11.8
  - cuda-runtime=11.8.0
  - ipykernel
  - ipython
  - jupyter_core
  - jupyter_client
  - requests
  - tqdm
  - pyyaml
  - psutil
  - zlib
  - zstd
  - blosc
  - openssl
  - ca-certificates
  - certifi
  - sqlite

  - pip:
      - careamics==0.1.0rc6
      - pytorch-lightning==2.3.0
      - torchmetrics==1.4.0.post0
      - bioimageio-core==0.6.7
      - scikit-image==0.24.0rc1
      - zarr==2.18.2
      - rich==13.7.1
      - pydantic==2.7.4
      - python-dotenv==1.0.1
